// ── 스타일 정의 SSOT (Single Source of Truth) ─────────────────────────
// 새 필터 추가/삭제 시 이 파일만 수정하면 studio, mypage, generate 등 자동 반영

export type StyleDef = {
  id: string;
  name: string;
  desc: string;
  bgColor: string;
  tag: string;
  active: boolean;
  hidden: boolean;
  beforeImg: string;
  afterImg: string;
  popular?: boolean;
};

export type StyleCategory = "일상" | "자연" | "무드" | "컨셉" | "스포츠";

export const STYLE_CATEGORY_TABS = ["전체", "일상", "자연", "무드", "컨셉", "스포츠"] as const;

export const STYLE_CATEGORY_BY_ID: Record<string, StyleCategory> = {
  gyaru: "컨셉",
  angel: "컨셉",
  "orange-cosmic-girl": "컨셉",
  "subway-cctv": "일상",
  "visual-kei": "컨셉",
  "idol-photocard": "무드",
  "club-flash": "무드",
  "flash-selfie": "일상",
  "grab-selfie": "일상",
  "voxel-character": "컨셉",
  "joseon-farmer": "컨셉",
  "red-carpet-glam": "컨셉",
  "dark-coquette": "무드",
  "datecam-film": "무드",
  "ulzzang-cam": "무드",
  "jjimjilbang-master": "컨셉",
  skydiving: "스포츠",
  "maid-cafe-heart": "컨셉",
  "hiphop-grillz": "컨셉",
  hellotokyo: "컨셉",
  "mongolian-warrior": "컨셉",
  "american-rugby-player": "스포츠",
  "american-cheerleader": "스포츠",
  "western-gunslinger": "컨셉",
  "drink-pov": "컨셉",
  "existential-studio": "무드",
  "transit-station-security": "컨셉",
  "luxury-bedroom-bag": "컨셉",
  "cinematic-horseback": "컨셉",
  "dreamy-wildflower": "자연",
  "dreamy-celebratory": "자연",
  "romantic-night-twoshot": "무드",
  astronaut: "컨셉",
  "ramen-hair": "컨셉",
  "claw-machine": "컨셉",
  "bronze-statue-bench": "컨셉",
  "yakuza": "컨셉",
};

export const ALL_STYLES: StyleDef[] = [
  {
    id: "gyaru",
    name: "나는 이제부터 갸루",
    desc: "2000년대 일본 프리쿠라 갸루 스타일로 변신",
    bgColor: "#2a0a1a",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/gyaru-before.jpg",
    afterImg: "/thumbnails/gyaru-after.jpg",
    popular: true,
  },
  {
    id: "angel",
    name: "천사 변신",
    desc: "타락천사부터 여리여리 천사까지, 나만의 천사 스타일",
    bgColor: "#0e0e1a",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/angel-before.jpg",
    afterImg: "/thumbnails/angel-after.jpg",
    popular: true,
  },
  {
    id: "orange-cosmic-girl",
    name: "오렌지 코스믹걸",
    desc: "네온 놀이공원과 플랫 스카이 블루 배경 중 골라 코스믹 히로인 무드로 변환",
    bgColor: "#08b5f0",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Orange_cosmic_girl-before.jpg?v=1",
    afterImg: "/thumbnails/Orange_cosmic_girl-after.jpg?v=1",
  },
  {
    id: "subway-cctv",
    name: "지하철 포착",
    desc: "붐비는 지하철 CCTV에 우연히 찍힌 듯한 로우파이 감시카메라 컷",
    bgColor: "#586574",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/subway-cctv-before.jpg?v=1",
    afterImg: "/thumbnails/subway-cctv-after.jpg?v=1",
  },
  {
    id: "visual-kei",
    name: "비주얼계 밴드 멤버",
    desc: "어두운 인더스트리얼 배경 위에 선 일본 비주얼계 밴드 멤버 무드의 글램 록 포트레이트",
    bgColor: "#242a35",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/visual-kei-before.jpg?v=1",
    afterImg: "/thumbnails/visual-kei-after.jpg?v=1",
  },
  {
    id: "romantic-night-twoshot",
    name: "둘이 선 밤도시",
    desc: "사진 2장을 올리면 밤 도시 야경 위 손잡은 로맨틱 시네마틱 투샷으로 변환",
    bgColor: "#1c2245",
    tag: "2인",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/romantic-night-twoshot-before.jpg?v=2",
    afterImg: "/thumbnails/romantic-night-twoshot-after.jpg?v=2",
    popular: true,
  },
  {
    id: "astronaut",
    name: "우주 비행사",
    desc: "별이 흩어진 우주 배경 앞에 선 한국 우주비행사 에디토리얼 포트레이트",
    bgColor: "#08111d",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/astronaut-before.jpg?v=1",
    afterImg: "/thumbnails/astronaut-after.jpg?v=1",
  },
  {
    id: "ramen-hair",
    name: "라면 머리",
    desc: "진지한 표정과 노란 면발 컬이 충돌하는 병맛 에디토리얼 포트레이트",
    bgColor: "#d1bb6d",
    tag: "MEME",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/ramen-hair-before.jpg?v=1",
    afterImg: "/thumbnails/ramen-hair-after.jpg?v=1",
  },
  {
    id: "claw-machine",
    name: "인형뽑기 속 나",
    desc: "형형색색 인형에 둘러싸여 뽑기 기계 안에 앉아 있는 위트 있는 아케이드 컷",
    bgColor: "#6f8ab2",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/claw-machine-before.jpg?v=1",
    afterImg: "/thumbnails/claw-machine-after.jpg?v=1",
  },
  {
    id: "idol-photocard",
    name: "아이돌 포토카드",
    desc: "포카 뽑고 싶은 맑고 반짝이는 아이돌 셀카 무드",
    bgColor: "#120d1f",
    tag: "TREND",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/idol-photocard-before.jpg?v=2",
    afterImg: "/thumbnails/idol-photocard-after.jpg?v=1",
  },
  {
    id: "club-flash",
    name: "클럽 플래시샷",
    desc: "새벽 파티에서 찍힌 강한 플래시 직격샷 분위기",
    bgColor: "#150d18",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/club-flash-before.jpg?v=2",
    afterImg: "/thumbnails/club-flash-after.jpg?v=1",
  },
  {
    id: "flash-selfie",
    name: "플래시 필터",
    desc: "플래시 터트린듯한 느낌 적용",
    bgColor: "#1a1010",
    tag: "무료",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/flash-before.jpg",
    afterImg: "/thumbnails/flash-after.jpg",
  },
  {
    id: "grab-selfie",
    name: "베트남 오토바이 셀카 필터",
    desc: "얼굴이 보이는 정확한 셀카 사진을 업로드해주세요.",
    bgColor: "#0e2a1a",
    tag: "무료",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/grab-before.jpg",
    afterImg: "/thumbnails/grab-after.jpg",
  },
  {
    id: "voxel-character",
    name: "픽셀 캐릭터 필터",
    desc: "사진 속 나를 블록으로 만든 3D 캐릭터로 변환",
    bgColor: "#0a1a2a",
    tag: "무료",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/voxel-before.jpg",
    afterImg: "/thumbnails/voxel-after.jpg",
  },
  {
    id: "joseon-farmer",
    name: "조선시대 농부",
    desc: "얼굴이 잘 보이는 정면 사진을 업로드해주세요.",
    bgColor: "#1a1408",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/joseon-before.jpg?v=2",
    afterImg: "/thumbnails/joseon-after.jpg?v=2",
    popular: true,
  },
  {
    id: "red-carpet-glam",
    name: "레드카펫 글램",
    desc: "시상식 포토월 앞에서 찍힌 셀럽 무드의 에디토리얼 컷",
    bgColor: "#1a1012",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/red-carpet-glam-before.jpg?v=1",
    afterImg: "/thumbnails/red-carpet-glam-after.jpg?v=1",
  },
  {
    id: "dark-coquette",
    name: "다크 코케트",
    desc: "블랙 레이스와 체리 포인트가 들어간 무드 있는 코케트",
    bgColor: "#170c12",
    tag: "TREND",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/dark-coquette-before.jpg?v=1",
    afterImg: "/thumbnails/dark-coquette-after.jpg?v=1",
  },
  {
    id: "datecam-film",
    name: "데이트캠 필름",
    desc: "흔들린 플래시와 필름 그레인이 살아있는 감성 데이트샷",
    bgColor: "#191512",
    tag: "FILM",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/datecam-film-before.jpg?v=1",
    afterImg: "/thumbnails/datecam-film-after.jpg?v=1",
  },
  {
    id: "ulzzang-cam",
    name: "얼짱캠 부활",
    desc: "뽀용 블러, 큰 눈 포인트, 2010년대 얼짱캠 감성 리메이크",
    bgColor: "#16131f",
    tag: "RETRO",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/ulzzang-cam-before.jpg",
    afterImg: "/thumbnails/ulzzang-cam-after.jpg?v=1",
  },
  {
    id: "jjimjilbang-master",
    name: "찜질방 만렙",
    desc: "양머리 수건부터 식혜까지 완벽한 K-찜질방 병맛짤",
    bgColor: "#3b2416",
    tag: "MEME",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/jjimjilbang-master-before.jpg?v=1",
    afterImg: "/thumbnails/jjimjilbang-master-after.jpg?v=1",
  },
  {
    id: "skydiving",
    name: "스카이다이빙",
    desc: "하늘 한복판 탠덤 점프 순간을 극한 스포츠 직찍처럼 변환",
    bgColor: "#132b52",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/skydiving-before.jpg?v=2",
    afterImg: "/thumbnails/skydiving-after.jpg?v=2",
  },
  {
    id: "maid-cafe-heart",
    name: "메이드카페 직원 💗",
    desc: "테마 카페에서 찍은 듯한 진심 가득 메이드카페 스냅샷",
    bgColor: "#2a1826",
    tag: "TREND",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/maid-cafe-heart-before.jpg?v=2",
    afterImg: "/thumbnails/maid-cafe-heart-after.jpg?v=2",
  },
  {
    id: "hiphop-grillz",
    name: "힙합 그릴즈 했어요 ✨",
    desc: "다이아 체인과 그릴즈가 강조된 하드한 힙합 에디토리얼 클로즈업",
    bgColor: "#13110f",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/hiphop-grillz-before.jpg?v=1",
    afterImg: "/thumbnails/hiphop-grillz-after.jpg?v=1",
  },
  {
    id: "hellotokyo",
    name: "헬로 도쿄",
    desc: "도쿄 팝 그래픽이 폭발하는 하이텐션 에디토리얼 콜라주 포스터",
    bgColor: "#171511",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/hellotokyo-before.jpg?v=1",
    afterImg: "/thumbnails/hellotokyo-after.jpg?v=1",
  },
  {
    id: "mongolian-warrior",
    name: "몽골의 전사",
    desc: "초원 위에 선 몽골 전사의 다큐멘터리풍 전신 인물사진",
    bgColor: "#2b3321",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Mongolian-before.jpg?v=1",
    afterImg: "/thumbnails/Mongolian-after.jpg?v=1",
  },
  {
    id: "american-rugby-player",
    name: "미국 럭비 선수",
    desc: "강한 햇빛 아래 질주하는 럭비 선수의 스포츠 액션 포트레이트",
    bgColor: "#14233a",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/rugby-before.jpg?v=1",
    afterImg: "/thumbnails/rugby-after.jpg?v=1",
  },
  {
    id: "american-cheerleader",
    name: "미쿡 치어리더 언니 💗",
    desc: "강한 조명 아래 체육관 코트에서 빛나는 치어리더 포트레이트",
    bgColor: "#21314a",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/cheerleader-before.jpg?v=1",
    afterImg: "/thumbnails/cheerleader-after.jpg?v=1",
  },
  {
    id: "western-gunslinger",
    name: "나는야 서부 총잡이",
    desc: "먼지 자욱한 서부 마을에서 포착된 총잡이의 시네마틱 영화 스틸",
    bgColor: "#3a281b",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/gunslinger-before.jpg?v=1",
    afterImg: "/thumbnails/gunslinger-after.jpg?v=1",
  },
  {
    id: "drink-pov",
    name: "음료 호로롭",
    desc: "빨간 슬러시 컵 안에서 올려다본 여름 음료 POV 라이프스타일 컷",
    bgColor: "#8e2f32",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Drink_POV-before.jpg?v=1",
    afterImg: "/thumbnails/Drink_POV-after.jpg?v=1",
  },
  {
    id: "existential-studio",
    name: "덩그러니 나 혼자 ✨",
    desc: "흰 스튜디오 한가운데 홀로 앉은 인물을 둘러싼 모션 블러 군중 컷",
    bgColor: "#d7dade",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Existential_studio-before.jpg?v=1",
    afterImg: "/thumbnails/Existential_studio-after.jpg?v=1",
  },
  {
    id: "transit-station-security",
    name: "CCTV에 포착된 나",
    desc: "지하철 개찰구 CCTV에 잡힌 듯한 장난기 있는 보안카메라 스틸",
    bgColor: "#4c4654",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Transit_station_securit-before.jpg?v=1",
    afterImg: "/thumbnails/Transit_station_securit-after.jpg?v=1",
  },
  {
    id: "luxury-bedroom-bag",
    name: "쇼핑백에 들어가자",
    desc: "침실 한가운데 초대형 쇼핑백 안에 들어간 럭셔리 라이프스타일 컷",
    bgColor: "#35543f",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Luxury_bedroom-before.jpg?v=1",
    afterImg: "/thumbnails/Luxury_bedroom-after.jpg?v=1",
  },
  {
    id: "cinematic-horseback",
    name: "백마탄 나",
    desc: "푸른 하늘 아래 백마 위에 앉은 시네마틱 패션 에디토리얼 포트레이트",
    bgColor: "#335b70",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Cinematic_horseback-before.jpg?v=1",
    afterImg: "/thumbnails/Cinematic_horseback-after.jpg?v=1",
  },
  {
    id: "dreamy-wildflower",
    name: "꽃밭 뒤돌아본 나",
    desc: "들꽃 가득한 여름 꽃밭에서 뒤돌아본 로맨틱 아웃도어 에디토리얼 컷",
    bgColor: "#acb6db",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Dreamy_wildflower-before.jpg?v=1",
    afterImg: "/thumbnails/Dreamy_wildflower-after.jpg?v=1",
  },
  {
    id: "dreamy-celebratory",
    name: "빛 쏟아진 순간",
    desc: "햇살과 컨페티가 번지는 코트야드에서 포착된 드리미 셀레브레이션 포트레이트",
    bgColor: "#324957",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Dreamy_celebratory-before.jpg?v=1",
    afterImg: "/thumbnails/Dreamy_celebratory-after.jpg?v=1",
  },
  {
    id: "bronze-statue-bench",
    name: "공원 벤치 청동상",
    desc: "한적한 공원 벤치에 앉은 청동 조형물처럼 바뀌는 리얼 파크 스냅 컷",
    bgColor: "#5a4637",
    tag: "HOT",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/Bronze-before.jpg?v=1",
    afterImg: "/thumbnails/Bronze-after.jpg?v=1",
  },
  {
    id: "yakuza",
    name: "어둠의 큰형님",
    desc: "야쿠자와 마피아 무드 중 하나를 골라 범죄 드라마 에디토리얼 포트레이트로 변환",
    bgColor: "#221a28",
    tag: "NEW",
    active: true,
    hidden: false,
    beforeImg: "/thumbnails/yakuza-before.jpg",
    afterImg: "/thumbnails/yakuza-after.jpg",
  },
];

/** UI에 표시되는 스타일만 (hidden === false) */
export const VISIBLE_STYLES = ALL_STYLES.filter((s) => !s.hidden);

/** 모든 스타일의 ID → 이름 매핑 */
export const STYLE_LABELS: Record<string, string> = Object.fromEntries(
  ALL_STYLES.map((s) => [s.id, s.name])
);

/** UI에 표시되는 스타일 ID 순서 배열 */
export const VISIBLE_STYLE_IDS = VISIBLE_STYLES.map((s) => s.id);

/** 다중 업로드가 필요한 스타일 ID */
export const MULTI_SOURCE_STYLE_IDS = ["romantic-night-twoshot"] as const;
